### PR TITLE
Make standalone — No Octopress plugins, scripts, etc.

### PR DESCRIPTION
**Pull request by rickychilcott**
Stripped out everything from Octopress that we weren't really using and it looks just about right. @benlachman or @timothywasserman can you check this out?

You should do a `bundle install --path .bundle` then do a `bundle exec jekyll serve` and check it out

### CODE REVIEW

**Comment by rickychilcott** [comment]
ping....

**Comment by benlachman** [comment]
I was just thinking about this…

**Comment by rickychilcott** [comment]
Does that mean to merge?

**Comment by benlachman** [comment]
I still like octopress for some of the stuff if you're actually doing a blog, but for our site this makes *total* sense. Merged.

**Pull request merged**
